[build]
  command = "npm run build"
  publish = "dist/jo2024Front/browser"

[context.production.environment]
  NETLIFY_USE_PRERENDER = "false"


# 🔄 Redirections pour Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
