[build]
  command = "npm run build"
  publish = "dist/jo2024Front/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# 🔄 Redirections pour Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
