[build]
  command = "npm run build"
  publish = "dist/jo2024Front/browser"

[build.environment]
  NETLIFY_USE_PRERENDER = "false"
  NETLIFY_SKIP_PRERENDER = "true"

# 🔄 Redirections pour Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
